apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: o5xwli8m6-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: o5xwli8m6-go 
  name: o5xwli8m6-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: o5xwli8m6-go 
